services:
  api-biblioteca:
    build: .
    container_name: servidor_biblioteca
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload